(function () {
  const fp8 = 1;
  const mxfp4 = 0.5;

  window.BALLPARK_MODELS = [
    {
      id: "glm-52",
      name: "GLM-5.2",
      accent: "#c9f36a",
      family: "DSA · IndexShare · MoE",
      scale: "744B / 40B",
      evidence: "REFERENCE FORWARD",
      dims: {
        H: 6144,
        heads: 64,
        qLatent: 2048,
        kvLatent: 512,
        qkNope: 192,
        qkRope: 64,
        valueHead: 256,
        indexHeads: 32,
        indexDim: 128,
        indexTopK: 2048,
        experts: 256,
        activeExperts: 8,
        sharedExperts: 1,
        expertHidden: 2048,
        vocabulary: 154880,
        layers: 78,
        denseLayers: 3,
        moeLayers: 75,
        indexShareGroup: 4,
        weightBytes: fp8,
        kvBytes: fp8,
        mtpAcceptDefault: 1,
      },
      parallel: { tp: 8, ep: 8, pp: 1, pdP: 1, pdD: 1, servingMode: "disaggregated" },
      cacheKind: "mla-compressed",
      layerKinds: { attention: "dsa-mla", ffn: "moe" },
      measuredTps: 68.86,
      measuredNote: "NVIDIA Dynamo 16×H200 1P1D · 64K/400 · 90% hit",
    },
    {
      id: "kimi-k3",
      name: "Kimi K3",
      accent: "#ff8d5b",
      family: "KDA · Gated MLA · LatentMoE",
      scale: "2.8T / 104B",
      evidence: "REFERENCE FORWARD",
      dims: {
        H: 7168,
        heads: 96,
        headDim: 128,
        qLatent: 1536,
        kvLatent: 512,
        qkRope: 64,
        experts: 896,
        activeExperts: 16,
        sharedExperts: 2,
        expertHidden: 3072,
        latent: 3584,
        vocabulary: 163840,
        layers: 93,
        kdaLayers: 69,
        mlaLayers: 24,
        denseLayers: 0,
        moeLayers: 93,
        weightBytes: mxfp4,
        kvBytes: fp8,
        mtpAcceptDefault: 1,
      },
      parallel: { tp: 8, ep: 16, pp: 1, pdP: 1, pdD: 1, servingMode: "disaggregated" },
      cacheKind: "hybrid-kda-mla",
      layerKinds: { attention: "kda-or-mla", ffn: "latent-moe" },
      measuredTps: 146.9 / 16,
      measuredNote: "SGLang 社区 16×H200 · 54 并发 · 未饱和下界",
    },
    {
      id: "kimi-k25",
      name: "Kimi K2.5",
      accent: "#83b8ff",
      family: "MLA · MoE",
      scale: "1T / 32B",
      evidence: "REFERENCE FORWARD",
      dims: {
        H: 7168,
        heads: 64,
        qLatent: 1536,
        kvLatent: 512,
        qkNope: 128,
        qkRope: 64,
        valueHead: 128,
        experts: 384,
        activeExperts: 8,
        sharedExperts: 1,
        expertHidden: 2048,
        denseHidden: 18432,
        vocabulary: 163840,
        layers: 61,
        denseLayers: 1,
        moeLayers: 60,
        weightBytes: 0.6,
        kvBytes: fp8,
        mtpAcceptDefault: 1,
      },
      parallel: { tp: 8, ep: 8, pp: 1, pdP: 1, pdD: 1, servingMode: "aggregated" },
      cacheKind: "mla-absorbed",
      layerKinds: { attention: "mla", ffn: "moe" },
      measuredTps: null,
      measuredNote: "Decode KV 按 serving absorbed 512+64 latent，不是 HF 展开 K/V。",
    },
    {
      id: "minimax-m3",
      name: "MiniMax M3",
      accent: "#c4a574",
      family: "Block-sparse GQA · MoE",
      scale: "428B / 23B",
      evidence: "SERVING FORWARD",
      dims: {
        H: 6144,
        heads: 64,
        kvHeads: 4,
        headDim: 128,
        indexTopK: 16,
        blockSize: 128,
        localBlocks: 1,
        experts: 128,
        activeExperts: 4,
        sharedExperts: 1,
        expertHidden: 3072,
        denseHidden: 12288,
        vocabulary: 200064,
        layers: 60,
        denseLayers: 3,
        moeLayers: 57,
        weightBytes: fp8,
        kvBytes: fp8,
        mtpAcceptDefault: 1,
      },
      parallel: { tp: 8, ep: 8, pp: 1, pdP: 1, pdD: 1, servingMode: "disaggregated" },
      cacheKind: "paged-gqa",
      layerKinds: { attention: "sparse-gqa", ffn: "moe" },
      measuredTps: null,
      measuredNote: "代表图画 layer 3+ 的 sparse GQA；前 3 层按 dense 满注意力计入层乘数。",
    },
  ];
}());
