(function () {
  const fp8 = 1;
  const mxfp4 = 0.5;

  window.BALLPARK_MODELS = [
    {
      id: "glm-52",
      name: "GLM-5.2",
      accent: "#111",
      family: "DSA · IndexShare · MoE",
      scale: "744B / 40B",
      evidence: "REFERENCE FORWARD",
      dims: {
        H: 6144,
        heads: 64,
        qLatent: 2048,
        kvLatent: 512,
        qkNope: 192,
        qkRope: 64,
        valueHead: 256,
        indexHeads: 32,
        indexDim: 128,
        indexTopK: 2048,
        experts: 256,
        activeExperts: 8,
        sharedExperts: 1,
        expertHidden: 2048,
        vocabulary: 154880,
        layers: 78,
        denseLayers: 3,
        moeLayers: 75,
        indexShareGroup: 4,
        weightBytes: fp8,
        kvBytes: fp8,
        mtpAcceptDefault: 1,
      },
      parallel: { tp: 8, ep: 8, pp: 1, pdP: 1, pdD: 1, servingMode: "aggregated", layout: "overlap" },
      cacheKind: "mla-compressed",
      layerKinds: { attention: "dsa-mla", ffn: "moe" },
      measuredTps: 1944.77 / 8,
      measuredNote: "GPUStack 8×H200 SGLang DeepEP+DP-attn · 8K/1K · 512 并发 · output 1945 tok/s 整机（headline Total TPS 17.5K 含输入）",
    },
    {
      id: "kimi-k3",
      name: "Kimi K3",
      accent: "#111",
      family: "KDA · Gated MLA · LatentMoE",
      scale: "2.8T / 104B",
      evidence: "REFERENCE FORWARD",
      dims: {
        H: 7168,
        heads: 96,
        headDim: 128,
        qLatent: 1536,
        kvLatent: 512,
        qkNope: 128,
        qkRope: 64,
        valueHead: 128,
        experts: 896,
        activeExperts: 16,
        sharedExperts: 2,
        expertHidden: 3072,
        latent: 3584,
        denseHidden: 33792,
        vocabulary: 163840,
        layers: 93,
        kdaLayers: 69,
        mlaLayers: 24,
        denseLayers: 1,
        moeLayers: 92,
        weightBytes: mxfp4,
        attnBytes: 2,
        denseBytes: 2,
        kvBytes: fp8,
        mtpAcceptDefault: 1,
      },
      parallel: { tp: 16, ep: 16, pp: 1, pdP: 1, pdD: 1, servingMode: "aggregated", layout: "overlap", attnMode: "tp" },
      cacheKind: "hybrid-kda-mla",
      layerKinds: { attention: "kda-or-mla", ffn: "latent-moe" },
      measuredTps: 146.9 / 16,
      measuredNote: "HF #136：16×H200 TP16+EP16 marlin · 54 并发未饱和 146.9 tok/s 整机。KDA 占 69/93 层，DP-attn 不是最优。",
    },
    {
      id: "kimi-k25",
      name: "Kimi K2.5",
      accent: "#111",
      family: "MLA · MoE",
      scale: "1T / 32B",
      evidence: "REFERENCE FORWARD",
      dims: {
        H: 7168,
        heads: 64,
        qLatent: 1536,
        kvLatent: 512,
        qkNope: 128,
        qkRope: 64,
        valueHead: 128,
        experts: 384,
        activeExperts: 8,
        sharedExperts: 1,
        expertHidden: 2048,
        denseHidden: 18432,
        vocabulary: 163840,
        layers: 61,
        denseLayers: 1,
        moeLayers: 60,
        weightBytes: 0.5,
        attnBytes: 2,
        denseBytes: 2,
        kvBytes: fp8,
        mtpAcceptDefault: 1,
      },
      parallel: { tp: 8, ep: 8, pp: 1, pdP: 1, pdD: 1, servingMode: "aggregated", layout: "overlap" },
      cacheKind: "mla-absorbed",
      layerKinds: { attention: "mla", ffn: "moe" },
      measuredTps: null,
      measuredNote: "INT4 只打 routed experts；self-attn / shared / 首层 dense / lm_head 仍是 BF16。Decode KV 按 absorbed 512+64。",
    },
    {
      id: "minimax-m3",
      name: "MiniMax M3",
      accent: "#111",
      family: "Block-sparse GQA · MoE",
      scale: "428B / 23B",
      evidence: "SERVING FORWARD",
      dims: {
        H: 6144,
        heads: 64,
        kvHeads: 4,
        headDim: 128,
        indexTopK: 16,
        blockSize: 128,
        localBlocks: 1,
        experts: 128,
        activeExperts: 4,
        sharedExperts: 1,
        expertHidden: 3072,
        denseHidden: 12288,
        vocabulary: 200064,
        layers: 60,
        denseLayers: 3,
        moeLayers: 57,
        weightBytes: 2,
        kvBytes: 2,
        mtpAcceptDefault: 1,
      },
      parallel: { tp: 8, ep: 8, pp: 1, pdP: 1, pdD: 1, servingMode: "aggregated", layout: "overlap" },
      cacheKind: "paged-gqa",
      layerKinds: { attention: "sparse-gqa", ffn: "moe" },
      measuredTps: 116,
      measuredNote: "HF MiniMax-M3 是 BF16；SGLang cookbook H200 热稳态约 116 tok/s/GPU。MXFP8 是另一份 Blackwell checkpoint。",
    },
  ];
}());
